del "*.suo" /S/Q/F/A
del "*.csproj.user" /S/Q/F/A
del "Reference.DiagnosisCodes.web.demo\bin\*.pdb" /Q
rd "Reference.DiagnosisCodes.web.demo\obj" /S/Q
rd "SuffixArray\bin" /S/Q
rd "SuffixArray\obj" /S/Q
rd "Reference.DiagnosisCodes.ConsoleApp\bin" /S/Q
rd "Reference.DiagnosisCodes.ConsoleApp\obj" /S/Q
rd "BPlusTree\bin" /S/Q
rd "BPlusTree\obj" /S/Q
